---
- name: Install Docker packages for Redhat
  become: yes
  yum:
    name: docker
    state: present
  when: ansible_os_family == 'RedHat'

- name: Install Docker packags for Debian
  become: yes
  apt:
    name: docker.io
    state: present
  when: ansible_os_family == 'Debian'
