---
- name: Install Docker packages
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
  when: ansible_os_family == 'RedHat'

- name: Install Docker Python library
  pip: name=docker-py state=present
  become: yes
  
- name: Enable Docker service
  become: true
  service:
    name: "docker.service"
    state: started
    enabled: yes
